### ISSUE TITLE
[FR] Would it be possible to integrate DFIR-IRIS additionally to this stack?

### ISSUE THREAD

**Issue by pandel** [dLoProdz/OSSIEM#3]

**Comment by dLoProdz** [comment]
Hi @pandel,

DFIR-IRIS has been deprecated in the SOCFortress stack since the CoPilot case management functionality was released. I recommend you take a look at that first, if it doesn't fit your needs then you can spin up a standalone Iris instance, but bear in mind that CoPilot no longer has a connector for it.

**Comment by pandel** [comment]
Hey @dLoProdz ! Many thanks and I am sorry, I did not know that. Makes totally sense then.
